### ISSUE TITLE
Example has incorrect repo name

### ISSUE THREAD

**Issue by sofbkeller** [actions-js/push#17]
Example shows the following: 

>       uses: actions-js/push@master
>       with:
>         github_token: ${{ secrets.GITHUB_TOKEN }}

It should be:
>       uses: Smart-Transportation/push@v1.3
>       with:
>         github_token: ${{ secrets.GITHUB_TOKEN }}

**Comment by devenes** [comment]
The action that you mentioned is a fork of this original repository https://github.com/actions-js/push/.
So if you want to use the latest features you need to this action.

```yaml
  uses: actions-js/push@master
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
```
