### ISSUE TITLE
Documentation update if using GitHub App

### ISSUE THREAD

**Issue by igitcode** [actions-js/push#27]
Not really an issue, but I need to use a GH app to bypass branch protection rules. So my configuration is as follows:

On git checkout, you must not persist credentials, otherwise they cannot be overridden by `github_token` input var:
```
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: 'false'
```

I used the `actions/create-github-app-token` action to generate token from GitHub App ID and PrivateKey.
```
      - uses: actions/create-github-app-token@v1
        id: app-token
```

I can use that token on this action as:
 ```
     - name: Commit Changes
        id: commit-changes
        uses: actions-js/push@v1.5
        with:
          github_token: ${{ steps.app-token.outputs.token }}
```
